// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace examinationSystem2.Models;

public partial class Course
{
    public int CrsId { get; set; }

    public string CrsName { get; set; }

    public int? CrsDuration { get; set; }

    public int? InsId { get; set; }

    public virtual Instructor Ins { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual ICollection<StdCourse> StdCourses { get; set; } = new List<StdCourse>();

    public virtual ICollection<Topic> Topics { get; set; } = new List<Topic>();

    public virtual ICollection<Department> Depts { get; set; } = new List<Department>();
}