// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace examinationSystem2.Models;

public partial class Exam
{
    public int ExamId { get; set; }

    public int? ExamDuration { get; set; }

    public virtual ICollection<StdExam> StdExams { get; set; } = new List<StdExam>();

    public virtual ICollection<Question> Ques { get; set; } = new List<Question>();
}