// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace examinationSystem2.Models;

public partial class Instructor
{
    public int InsSsn { get; set; }

    public string InsFname { get; set; }

    public string InsLname { get; set; }

    public string InsPhone { get; set; }

    public int? InsSalary { get; set; }

    public string InsAddress { get; set; }

    public int? DeptId { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual Department Dept { get; set; }
}