// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace examinationSystem2.Models;

public partial class QuesChoice
{
    public int QuesId { get; set; }

    public string QuesChoices { get; set; }

    public virtual Question Ques { get; set; }
}