// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace examinationSystem2.Models;

public partial class Question
{
    public int QuesId { get; set; }

    public string QuesType { get; set; }

    public string QuesBody { get; set; }

    public string QuesAnswer { get; set; }

    public int QuesGrade { get; set; }

    public int? CrsId { get; set; }

    public virtual Course Crs { get; set; }

    public virtual ICollection<QuesChoice> QuesChoices { get; set; } = new List<QuesChoice>();

    public virtual ICollection<StdExam> StdExams { get; set; } = new List<StdExam>();

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}