// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examinationSystem2.Models
{
    public partial class SP_InstructorInfoResult
    {
        [Column("Course Name")]
        public string CourseName { get; set; }
        public int? Students { get; set; }
    }
}
