// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examinationSystem2.Models
{
    public partial class SP_ReopSTDCourseGradeResult
    {
        public string StudentName { get; set; }
        public string Crs_Name { get; set; }
        public int? Grade { get; set; }
        public int Crs_ID { get; set; }
    }
}
