// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examinationSystem2.Models
{
    public partial class SP_SelectDepartmentResult
    {
        public int Dept_ID { get; set; }
        public string Dept_Name { get; set; }
        public int? Manager_ID { get; set; }
    }
}
