// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examinationSystem2.Models
{
    public partial class SP_SelectInstructorResult
    {
        public int Ins_SSN { get; set; }
        public string Ins_Fname { get; set; }
        public string Ins_Lname { get; set; }
        public string Ins_Phone { get; set; }
        public int? Ins_Salary { get; set; }
        public string Ins_Address { get; set; }
        public int? Dept_ID { get; set; }
    }
}
