// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examinationSystem2.Models
{
    public partial class SP_SelectExamResult
    {
        public int Exam_ID { get; set; }
        public int? Exam_Duration { get; set; }
    }
}
