// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examinationSystem2.Models
{
    public partial class SP_StudentExamAnsResult
    {
        public string Department { get; set; }
        public string Student { get; set; }
        public string Question { get; set; }
        [Column("Model Answer")]
        public string ModelAnswer { get; set; }
        [Column("Student Answer")]
        public string StudentAnswer { get; set; }
    }
}
