// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace examinationSystem2.Models
{
    public partial class SP_SelectTopicsByCourseResult
    {
        public int Crs_ID { get; set; }
        public int Topic_ID { get; set; }
        public string Topic_Name { get; set; }
    }
}
