// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace examinationSystem2.Models;

public partial class StdCourse
{
    public int StId { get; set; }

    public int CrsId { get; set; }

    public int? Grade { get; set; }

    public virtual Course Crs { get; set; }

    public virtual Student St { get; set; }
}