// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace examinationSystem2.Models;

public partial class StdExam
{
    public int StSsn { get; set; }

    public int ExamId { get; set; }

    public int QuesId { get; set; }

    public string StAnswer { get; set; }

    public int? CrsId { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Question Ques { get; set; }

    public virtual Student StSsnNavigation { get; set; }
}