// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using examinationSystem2.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace examinationSystem2.Context
{
    public partial interface ISQL_ProjectContextProcedures
    {
        Task<List<SP_DeleteCourseResult>> SP_DeleteCourseAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_DeleteDepartmentResult>> SP_DeleteDepartmentAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_DeleteDeptCourseResult>> SP_DeleteDeptCourseAsync(int? dept, int? crs, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_DeleteExamResult>> SP_DeleteExamAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_DeleteExamQuesResult>> SP_DeleteExamQuesAsync(int? exam_id, int? ques_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_DeleteQuesAnswerResult>> SP_DeleteQuesAnswerAsync(int? ques_id, string answer, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_DeleteQuesChoiceResult>> SP_DeleteQuesChoiceAsync(int? Ques, string Choice, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_DeleteQuestionResult>> SP_DeleteQuestionAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_DeleteStdCourseResult>> SP_DeleteStdCourseAsync(int? StdID, int? CrsID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_DeleteStdExamResult>> SP_DeleteStdExamAsync(int? St_SSN, int? Exam_ID, int? Ques_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_DeleteStudentResult>> SP_DeleteStudentAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_DeptStudentsInfoResult>> SP_DeptStudentsInfoAsync(int? dept_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_ExamAnswersAsync(int? examID, int? stID, int? crsID, string a1, string a2, string a3, string a4, string a5, string a6, string a7, string a8, string a9, string a10, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ExamCorrectionResult>> SP_ExamCorrectionAsync(int? examID, int? stID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ExamGenerationResult>> SP_ExamGenerationAsync(int? crs, int? mcq, int? tf, int? dur, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ExamQuestionsResult>> SP_ExamQuestionsAsync(int? exam_no, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetStdCoursesResult>> SP_GetStdCoursesAsync(int? stID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_InsertCourseResult>> SP_InsertCourseAsync(string name, int? ins, int? duration, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_InsertDepartmentResult>> SP_InsertDepartmentAsync(string name, int? ins, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_InsertDeptCourseResult>> SP_InsertDeptCourseAsync(string dept, string crs, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_InsertExamResult>> SP_InsertExamAsync(int? duration, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_InsertExamQuesResult>> SP_InsertExamQuesAsync(int? examID, int? crsID, int? num, string type, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_InsertInstructorResult>> SP_InsertInstructorAsync(string Fname, string Lname, string Phone, decimal? Salary, string Ins_Address, int? Ins_Dept_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_InsertQuesChoiceResult>> SP_InsertQuesChoiceAsync(int? Ques, string Choice, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_InsertQuestionResult>> SP_InsertQuestionAsync(string body, string type, string answer, int? grade, int? crs_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_InsertStdCourseResult>> SP_InsertStdCourseAsync(int? StdID, int? CrsID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_InsertStdExamResult>> SP_InsertStdExamAsync(int? St_SSN, int? Exam_ID, int? Ques_ID, string St_Answer, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_InsertStudentResult>> SP_InsertStudentAsync(string FName, string LName, string Phone, string Address, DateOnly? BirthDate, int? DeptID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_InstructorInfoResult>> SP_InstructorInfoAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_logINResult>> SP_logINAsync(string SSN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ReopSTDCourseGradeResult>> SP_ReopSTDCourseGradeAsync(int? stdID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RepoExamQuestionsResult>> SP_RepoExamQuestionsAsync(int? exam_no, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RepoStudentAnsResult>> SP_RepoStudentAnsAsync(int? CrsID, int? stID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectCourseResult>> SP_SelectCourseAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectDepartmentResult>> SP_SelectDepartmentAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectDeptCourseResult>> SP_SelectDeptCourseAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectExamResult>> SP_SelectExamAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectExamQuesResult>> SP_SelectExamQuesAsync(int? exam_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectInstructorResult>> SP_SelectInstructorAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectQuesChoicesResult>> SP_SelectQuesChoicesAsync(int? Ques, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectQuestionResult>> SP_SelectQuestionAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectStdCourseResult>> SP_SelectStdCourseAsync(int? stdID, int? CrsID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectStdExamResult>> SP_SelectStdExamAsync(int? St_SSN, int? Exam_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectStudentResult>> SP_SelectStudentAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectTopicsResult>> SP_SelectTopicsAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_SelectTopicsByCourseResult>> SP_SelectTopicsByCourseAsync(int? Crs_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_STDCourseGradeResult>> SP_STDCourseGradeAsync(int? stdID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_StudentExamAnsResult>> SP_StudentExamAnsAsync(int? examID, int? stID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UpdateCourseResult>> SP_UpdateCourseAsync(int? id, string name, int? ins, int? duration, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UpdateDepartmentResult>> SP_UpdateDepartmentAsync(int? id, string name, int? ins, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UpdateDeptCourseResult>> SP_UpdateDeptCourseAsync(int? dept, int? crs, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UpdateExamResult>> SP_UpdateExamAsync(int? id, int? duration, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UpdateExamQuesResult>> SP_UpdateExamQuesAsync(int? exam_id, int? ques_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UpdateQuesChoiceResult>> SP_UpdateQuesChoiceAsync(int? Ques, string Choice, string NewChoice, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UpdateQuestionResult>> SP_UpdateQuestionAsync(int? id, string body, string type, string answer, int? grade, int? crs_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UpdateStdCourseResult>> SP_UpdateStdCourseAsync(int? StdID, int? CrsID, int? newCrs, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UpdateStdExamResult>> SP_UpdateStdExamAsync(int? St_SSN, int? Exam_ID, int? Ques_ID, string St_Answer, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UpdateStudentResult>> SP_UpdateStudentAsync(int? ID, string FName, string LName, string Phone, string Address, DateOnly? BirthDate, int? DeptID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UpdateTopicResult>> SP_UpdateTopicAsync(string Topic_name, int? Crs_ID, string newTopic, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
